#pragma once

#include "NativeGameplayTags.h"

// 포켓몬 애니메이션
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Idle);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Idle_01);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Idle_02);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_BattleIdle);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Walk);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Run);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Turn_Left90);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Turn_Right90);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Jump_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Jump_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Fall_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Fall_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Land);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Attack_01);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Attack_02);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_RangeAttack_01);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_RangeAttack_02_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_RangeAttack_02_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_RangeAttack_02_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Damage_01);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Damage_02);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Stun_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Stun_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Stun_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Down_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Down_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Down_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Eat_01_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Eat_01_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Eat_01_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Eat_02_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Eat_02_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Eat_02_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Sleep_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Sleep_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Sleep_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Rest_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Rest_Loop);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Rest_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Notice);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Roar);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Glad);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Hate);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Refresh);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_StepOut_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_StepOut);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_StepOut_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Eye);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Animation_Mouth);

// 포켓몬 상태
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Idle);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Moving);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Jumping);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Falling);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_InCombat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Attacking);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Stunned);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Down);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Dead);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Eating);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_State_Sleeping);

// 포켓몬 이벤트, 어빌리티, 쿨다운
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Event_Attack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Event_RangeAttack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Event_Damage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Event_Stun);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Event_Down);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Event_Notice);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Event_Death);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Ability_BasicAttack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Ability_Skill);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Cooldown_BasicAttack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pokemon_Cooldown_Skill);
